### ISSUE TITLE
Dynamic require of \"crypto\" is not supported

### ISSUE THREAD

**Issue by jimsalyer** [willfarrell/middy-rds#7] opened 2023-05-22 13:39 UTC
I'm getting the error ""Dynamic require of \"crypto\" is not supported" when I try to use the middy-rds middleware in a JS module file (".mjs" extension). Is there a way around this, or am I stuck having to use this middlware only in ".js" and ".cjs" files? Here's the full stack trace for context.

```json
{
  "errorType": "Error",
  "errorMessage": "Dynamic require of \"crypto\" is not supported",
  "stack": [
    "Error: Dynamic require of \"crypto\" is not supported",
    "    at file:///var/task/node_modules/middy-rds/clients/pg.mjs:12:9",
    "    at node_modules/uuid/dist/rng.js (file:///var/task/node_modules/middy-rds/clients/pg.mjs:2451:42)",
    "    at __require2 (file:///var/task/node_modules/middy-rds/clients/pg.mjs:15:50)",
    "    at node_modules/uuid/dist/v1.js (file:///var/task/node_modules/middy-rds/clients/pg.mjs:2536:39)",
    "    at __require2 (file:///var/task/node_modules/middy-rds/clients/pg.mjs:15:50)",
    "    at node_modules/uuid/dist/index.js (file:///var/task/node_modules/middy-rds/clients/pg.mjs:2919:37)",
    "    at __require2 (file:///var/task/node_modules/middy-rds/clients/pg.mjs:15:50)",
    "    at node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js (file:///var/task/node_modules/middy-rds/clients/pg.mjs:3027:18)",
    "    at __require2 (file:///var/task/node_modules/middy-rds/clients/pg.mjs:15:50)",
    "    at node_modules/@aws-sdk/middleware-retry/dist-cjs/AdaptiveRetryStrategy.js (file:///var/task/node_modules/middy-rds/clients/pg.mjs:3135:35)"
  ]
}
```

**Comment by willfarrell** [comment] 2023-05-22 14:57
This is caused by `@aws-sdk/rds-signer` and their use of `uuid`.

If you're using esbuild, you can add `--banner:js` to overcome this:
```
node_modules/.bin/esbuild ${1} \
		--platform=node --format=esm  --target=node18 --bundle \
		--banner:js="import { createRequire } from 'module';const require = (m) => { if (m === './reserved.js') return {}; return createRequire(import.meta.url)(m);};const __dirname='.';" \
		--external:pg-native \
		--legal-comments=external --sourcemap=external \
		--allow-overwrite --outfile=${1%.js}.mjs
```

Additionally it looks like when I switched to aws sdk v3 the external flag wasn't updated which might also contribute to this issue. I just pushed a fix for this.

**Closed as completed by willfarrell** 2023-05-22 14:57 UTC

**Comment by jimsalyer** [comment] 2023-05-22 15:44
Thank you for the quick reply and update! Much appreciated!
